var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/dossier-clinique/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04s8u6a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0dnix45.js")
R.c("server/chunks/ssr/node_modules_next_dist_0en5di~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0of2swj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ulps9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0rmv67c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09ikpu.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_dossier-clinique_page_actions_0d5c6k7.js")
R.m(94156)
module.exports=R.m(94156).exports
