var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/a-propos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u5jr.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0fb~x1u.js")
R.c("server/chunks/ssr/node_modules_next_dist_0en5di~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0of2swj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ulps9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0rmv67c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09ikpu.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_a-propos_page_actions_06oljih.js")
R.m(50574)
module.exports=R.m(50574).exports
